apiVersion: v2
name: helm-librenms
description: LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system.

type: application
version: 0.1.0
appVersion: "21.11.0"

dependencies:
- name: redis
  version: "~16.9.11"
  repository: "https://charts.bitnami.com/bitnami"
  when: redis.enabled == true
- name: mysql
  version: "~9.2.0"
  repository: "https://charts.bitnami.com/bitnami"
  when: mysql.enabled == true
