apiVersion: v2
name: helm-librenms
description: A Helm chart for Kubernetes

type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
- name: redis
  version: "~16.9.11"
  repository: "https://charts.bitnami.com/bitnami"
  when: redis.enabled == true
- name: mysql
  version: "~9.2.0"
  repository: "https://charts.bitnami.com/bitnami"
  when: mysql.enabled == true
