apiVersion: v2
name: librenms
description: LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system.

type: application
version: 3.5.3
appVersion: "23.11.0"

dependencies:
- name: redis
  version: "~19.1.0"
  repository: "https://charts.bitnami.com/bitnami"
  when: redis.enabled == true
- name: mysql
  version: "~9"
  repository: "https://charts.bitnami.com/bitnami"
  when: mysql.enabled == true
